### ISSUE TITLE
Change of syntax with Network2.0 and upwards

### ISSUE THREAD

**Issue by wjcottam** [mattcieslak/easy_lausanne#6]
Hi,

I've been getting the following error after running easy_lausanne 

Traceback (most recent call last):
  File "/usr/bin/easy_lausanne", line 5, in <module>
    pkg_resources.run_script('Easy-Lausanne==0.5', 'easy_lausanne')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in run_script
    exec_(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/Easy_Lausanne-0.5-py2.7.egg/EGG-INFO/scripts/easy_lausanne", line 86, in <module>

  File "build/bdist.linux-x86_64/egg/easy_lausanne/maskcreation.py", line 234, in create_roi
AttributeError: 'Graph' object has no attribute 'nodes_iter'

... Which looks like it could be to do with the change from "nodes_iter()" method to "nodes()"

**Comment by AlexChalard** [comment]
Hello @wjcottam,
Did you find the solution for this issue ?
